### ISSUE TITLE
[BUG]Weld import

### ISSUE THREAD

**Issue by dataneodev** [idea-statica/ideastatica-public#26] opened 2021-04-30 08:15 UTC
Hi.

Since version 20.1 idea import welds incorrectly.
We still have to use the version 20.0.
This error has already been reported by me several times.
The problem occurs when the same elements have several welds.

I have prepared a few cases:

1. Beam and rib:

Location of these three weld not depends on Point defined in OpenModel.Connection.WeldData but rather in order of adding in the open model.

O1 - O3 is order in openModel , O1 - on the top ... O3 - on the bottom

![image](https://user-images.githubusercontent.com/38402428/116662978-c463de80-a996-11eb-96ec-f756dccf37cb.png)
![image](https://user-images.githubusercontent.com/38402428/116663067-e3fb0700-a996-11eb-95cd-a4269ab09a40.png)

Some ex:
a)
![image](https://user-images.githubusercontent.com/38402428/116662443-148e7100-a996-11eb-93ed-0ddf0948a5c0.png)
![image](https://user-images.githubusercontent.com/38402428/116664216-74861700-a998-11eb-9ce7-4622d45106c0.png)

[OpenModel_z.zip](https://github.com/idea-statica/iom-examples/files/6403597/OpenModel_z.zip)

b)
![image](https://user-images.githubusercontent.com/38402428/116663517-80bda480-a997-11eb-9a13-526cfd2f1982.png)
![image](https://user-images.githubusercontent.com/38402428/116663877-fc1f5600-a997-11eb-8e0f-3840a5e9abe9.png)

[OpenModel_N.zip](https://github.com/idea-statica/iom-examples/files/6403639/OpenModel_N.zip)

2. Plate to beam
![image](https://user-images.githubusercontent.com/38402428/116665335-f1fe5700-a999-11eb-8025-89d814811cfb.png)
![image](https://user-images.githubusercontent.com/38402428/116665908-a00a0100-a99a-11eb-87f1-5dfd70968623.png)

[OpenModelResult_7.zip](https://github.com/idea-statica/iom-examples/files/6403716/OpenModelResult_7.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - IOM Version 21.0.15
 - IdeaStatiCa Version 21.0.0.3277

**Comment by TekuSP** [comment] 2021-05-04 08:15
Hi!

I am sorry you had to create this bug multiple times, we assigned this bug to development team and we will inform you about our progress.
Hopefully we will resolve the issue soon.

Thank you.

Richard Torhan

**Comment by vadura-pavel** [comment] 2021-05-17 13:04
Hello,
In the new version v21 the import of welds was improved. I suggest start testing with new version. However, there is another issue in your model. The problem is in the specification of a weld point.
When we import welds, we try to find a pair of plates (in your example Plate_01 and the plate of beam HEA300 S235 01), which touch each other, or their edges are very close. The weld point specifies which pair of plates should be selected. Your weld points aren´t located in close surrounding of intersecting plate edges and this causes problems.
During the import we know you want to weld Plate_01, but can't identify to which plate of beam (Top flange, Bottom flange or Web) should be welded. The safest bet is to specify the weld point somewhere along the connected edge of the plate.

**Comment by dataneodev** [comment] 2021-07-07 11:06
Hi.

Yes, in my OpenModels weld usually are located on one of the edges of the plate.
![image](https://user-images.githubusercontent.com/38402428/124745803-7af8b800-df20-11eb-8989-ed696806b030.png)
I write some code to move the point to plate center.

But i tested now, weld point is in center of bottom plange, after import weld is in top flange.
Please take a look. 
Or I don't understand something.

![image](https://user-images.githubusercontent.com/38402428/124748727-c06ab480-df23-11eb-93bf-0858d6e3be3c.png)
![image](https://user-images.githubusercontent.com/38402428/124748807-d5dfde80-df23-11eb-97cd-7dcbb3b6d788.png)
![image](https://user-images.githubusercontent.com/38402428/124748841-e09a7380-df23-11eb-8a70-44be1e2c5ada.png)
![image](https://user-images.githubusercontent.com/38402428/124748902-ef812600-df23-11eb-94de-bf4621b60b41.png)
[OpenModel_T.zip](https://github.com/idea-statica/ideastatica-public/files/6776606/OpenModel_T.zip)

**Comment by vojtech-chalupa** [comment] 2021-07-23 13:48
Thanks for the test case, this should indeed work and I couldn't figure out why it doesn't. There seems to be a bug in our algorithm which assigns a plate of a member to be welded based on the weld point position. I've planned the investigation and fix for the next week.

**Comment by mpospisil** [comment] 2021-09-16 07:56
it is resolved in the next patch

**Closed by mpospisil** 2021-09-16 07:56 UTC
Labels: bug

**Comment by dataneodev** [comment] 2021-09-21 08:27
wow
![idea](https://user-images.githubusercontent.com/38402428/134137940-094bfbd3-8bdc-40d3-bfdf-69b7356ee8b9.png)

**Comment by vojtech-chalupa** [comment] 2021-09-27 11:37
Wow, indeed. Sorry on behalf of mpospisil. The fix has actually not been merged into the patch (21.0.4), but the new release (21.1). This is coming out in a week or so:

![image](https://user-images.githubusercontent.com/73105487/134900789-018e5f98-7a2e-4a2c-b440-bfa7e1b9f909.png)

**Comment by dataneodev** [comment] 2021-09-28 08:43
Thank you. We are looking forward to this feature
